add_test([=[SplashScreenTest.SplashScreenDuration]=]  D:/Projects/CPP/quick-vanish/Debug/qvanish-ut.exe [==[--gtest_filter=SplashScreenTest.SplashScreenDuration]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SplashScreenTest.SplashScreenDuration]=]  PROPERTIES WORKING_DIRECTORY D:/Projects/CPP/quick-vanish SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SplashScreenTest.SplashScreenException]=]  D:/Projects/CPP/quick-vanish/Debug/qvanish-ut.exe [==[--gtest_filter=SplashScreenTest.SplashScreenException]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SplashScreenTest.SplashScreenException]=]  PROPERTIES WORKING_DIRECTORY D:/Projects/CPP/quick-vanish SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SplashScreenTest.SplashScreenZero]=]  D:/Projects/CPP/quick-vanish/Debug/qvanish-ut.exe [==[--gtest_filter=SplashScreenTest.SplashScreenZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SplashScreenTest.SplashScreenZero]=]  PROPERTIES WORKING_DIRECTORY D:/Projects/CPP/quick-vanish SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LogSystemTest.LogSuccessSingle]=]  D:/Projects/CPP/quick-vanish/Debug/qvanish-ut.exe [==[--gtest_filter=LogSystemTest.LogSuccessSingle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LogSystemTest.LogSuccessSingle]=]  PROPERTIES WORKING_DIRECTORY D:/Projects/CPP/quick-vanish SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  qvanish-ut_TESTS SplashScreenTest.SplashScreenDuration SplashScreenTest.SplashScreenException SplashScreenTest.SplashScreenZero LogSystemTest.LogSuccessSingle)
