add_test([=[SplashScreenTest.SplashScreenSkipTest]=]  D:/Projects/CPP/quick-vanish/Debug/qvanish-ut.exe [==[--gtest_filter=SplashScreenTest.SplashScreenSkipTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SplashScreenTest.SplashScreenSkipTest]=]  PROPERTIES WORKING_DIRECTORY D:/Projects/CPP/quick-vanish SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SplashScreenTest.SplashScreenNormalTest]=]  D:/Projects/CPP/quick-vanish/Debug/qvanish-ut.exe [==[--gtest_filter=SplashScreenTest.SplashScreenNormalTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SplashScreenTest.SplashScreenNormalTest]=]  PROPERTIES WORKING_DIRECTORY D:/Projects/CPP/quick-vanish SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  qvanish-ut_TESTS SplashScreenTest.SplashScreenSkipTest SplashScreenTest.SplashScreenNormalTest)
